# https://rust-lang.github.io/rustfmt/?version=master&search=fn_call_#use_small_heuristics
hard_tabs = true
max_width = 120
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 36
array_width = 80
chain_width = 80
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
